// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "autotranslate",
    "name": "Autotranslate",
    "description": "Autotranslate plugin for Mattermost 5.22 and later.",
    "homepage_url": "https://github.com/mattermost/mattermost-plugin-autotranslate",
    "support_url": "https://github.com/mattermost/mattermost-plugin-autotranslate/issues",
    "release_notes_url": "https://github.com/mattermost/mattermost-plugin-autotranslate/releases/tag/v0.4.0",
    "version": "0.4.0",
    "min_server_version": "5.22.0",
    "server": {
        "executables": {
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": [
            {
                "key": "ScalewaySecretKey",
                "display_name": "Scaleway Secret Key:",
                "type": "text",
                "help_text": "The Scaleway API key used as the Bearer token for Generative APIs.",
                "placeholder": "",
                "default": null
            },
            {
                "key": "ScalewayProjectID",
                "display_name": "Scaleway Project ID:",
                "type": "text",
                "help_text": "Optional. Used to scope the API base URL to a specific Scaleway project.",
                "placeholder": "",
                "default": null
            },
            {
                "key": "ScalewayModel",
                "display_name": "Scaleway Model:",
                "type": "text",
                "help_text": "The Scaleway model ID used for translation requests.",
                "placeholder": "",
                "default": "mistral-small-3.2-24b-instruct-2506"
            },
            {
                "key": "ScalewayBaseURL",
                "display_name": "Scaleway Base URL:",
                "type": "text",
                "help_text": "Optional. Leave empty to use the default Scaleway Generative APIs URL or the project-scoped URL when Project ID is set.",
                "placeholder": "",
                "default": null
            },
            {
                "key": "ScalewaySystemPrompt",
                "display_name": "Scaleway System Prompt:",
                "type": "text",
                "help_text": "Optional. Overrides the default translation system prompt.",
                "placeholder": "",
                "default": null
            }
        ]
    }
}
`);

export default manifest;
export const id = manifest.id;
export const version = manifest.version;
